spring.application.name=Workflow-Management

spring.datasource.url=jdbc:mysql://zephyr.proxy.rlwy.net:13011/railway?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=SQriuXdzoEdMNEURZZLwMXdZeOnPEjoV

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}